const now = new Date()
const YEAR = now.getFullYear()
const MONTH = now.getMonth() // 0 = January, 10 = November, etc.

const mkDate = (day: number) =>
  new Date(YEAR, MONTH, day, 10, 0, 0, 0).toISOString()

export const todos = [
  {
    id: 1,
    todo: "Do something nice for someone you care about",
    completed: false,
    userId: 152,
    email: "sdfsdjhsdfjdsfdfkjsfkjsdfklf",
    name: "John Doesdfdfsdfdsf",
    nsdf: "sdsdfdsfdsfdsfdsff",
    sdf: "sdf",
    sdfsd: "sdf",
    sdfsdf: "sdf",
    sd: "sdf",
    array: ["kindness", "personal","important"],
    date: mkDate(1),
  },
  {
    id: 2,
    todo: "Memorize a poem",
    completed: true,
    userId: 13,
    array: ["learning"],
    date: mkDate(2),
  },
  {
    id: 3,
    todo: "Watch a classic movie",
    completed: true,
    userId: 68,
    array: ["entertainment"],
    date: mkDate(3),
  },
  {
    id: 4,
    todo: "Watch a documentary",
    completed: false,
    userId: 84,
    array: ["education"],
    date: mkDate(4),
  },
  {
    id: 5,
    todo: "Invest in cryptocurrency",
    completed: false,
    userId: 163,
    array: ["finance"],
    date: mkDate(5),
  },
  {
    id: 6,
    todo: "Contribute code or a monetary donation to an open-source software project",
    completed: false,
    userId: 69,
    array: ["open-source", "coding"],
    date: mkDate(6),
  },
  {
    id: 7,
    todo: "Solve a Rubik's cube",
    completed: true,
    userId: 76,
    array: ["puzzle"],
    date: mkDate(7),
  },
  {
    id: 8,
    todo: "Bake pastries for yourself and neighbor",
    completed: true,
    userId: 198,
    array: ["cooking", "social"],
    date: mkDate(8),
  },
  {
    id: 9,
    todo: "Go see a Broadway production",
    completed: false,
    userId: 7,
    array: ["theatre"],
    date: mkDate(9),
  },
  {
    id: 10,
    todo: "Write a thank you letter to an influential person in your life",
    completed: true,
    userId: 9,
    array: ["gratitude"],
    date: mkDate(10),
  },
  {
    id: 11,
    todo: "Invite some friends over for a game night",
    completed: false,
    userId: 104,
    array: ["social"],
    date: mkDate(11),
  },
  {
    id: 12,
    todo: "Have a football scrimmage with some friends",
    completed: false,
    userId: 32,
    array: ["sports"],
    date: mkDate(12),
  },
  {
    id: 13,
    todo: "Text a friend you haven't talked to in a long time",
    completed: true,
    userId: 2,
    array: ["social", "communication"],
    date: mkDate(13),
  },
  {
    id: 14,
    todo: "Organize pantry",
    completed: false,
    userId: 46,
    array: ["home"],
    date: mkDate(14),
  },
  {
    id: 15,
    todo: "Buy a new house decoration",
    completed: true,
    userId: 105,
    array: ["shopping", "home"],
    date: mkDate(15),
  },
  {
    id: 16,
    todo: "Plan a vacation you've always wanted to take",
    completed: true,
    userId: 162,
    array: ["travel"],
    date: mkDate(16),
  },
  {
    id: 17,
    todo: "Clean out car",
    completed: false,
    userId: 71,
    array: ["maintenance"],
    date: mkDate(17),
  },
  {
    id: 18,
    todo: "Draw and color a Mandala",
    completed: true,
    userId: 6,
    array: ["art"],
    date: mkDate(18),
  },
  {
    id: 19,
    todo: "Create a cookbook with favorite recipes",
    completed: true,
    userId: 53,
    array: ["cooking", "creative"],
    date: mkDate(19),
  },
  {
    id: 20,
    todo: "Bake a pie with some friends",
    completed: false,
    userId: 162,
    array: ["cooking", "social"],
    date: mkDate(20),
  },
  {
    id: 21,
    todo: "Create a compost pile",
    completed: false,
    userId: 13,
    array: ["environment"],
    date: mkDate(21),
  },
  {
    id: 22,
    todo: "Take a hike at a local park",
    completed: true,
    userId: 37,
    array: ["outdoors", "health"],
    date: mkDate(22),
  },
  {
    id: 23,
    todo: "Take a class at local community center that interests you",
    completed: true,
    userId: 65,
    array: ["learning", "community"],
    date: mkDate(23),
  },
  {
    id: 24,
    todo: "Research a topic interested in",
    completed: true,
    userId: 130,
    array: ["research"],
    date: mkDate(24),
  },
  {
    id: 25,
    todo: "Plan a trip to another country",
    completed: false,
    userId: 140,
    array: ["travel", "planning"],
    date: mkDate(25),
  },
  {
    id: 26,
    todo: "Improve touch typing",
    completed: false,
    userId: 178,
    array: ["learning", "productivity"],
    date: mkDate(26),
  },
  {
    id: 27,
    todo: "Learn Express.js",
    completed: false,
    userId: 194,
    array: ["coding", "web"],
    date: mkDate(27),
  },
  {
    id: 28,
    todo: "Learn calligraphy",
    completed: false,
    userId: 80,
    array: ["art", "hobby"],
    date: mkDate(28),
  },
  {
    id: 29,
    todo: "Have a photo session with some friends",
    completed: true,
    userId: 91,
    array: ["photography", "social"],
    date: mkDate(29),
  },
  {
    id: 30,
    todo: "Go to the gym",
    completed: true,
    userId: 142,
    array: ["health"],
    date: mkDate(30),
  },
]
