import { GlobalAlert } from '@/components/Alert'
import { ClientAlertProvider } from '@/components/ClientAlertProvider'
import { ClientSidebarProvider } from '@/components/ClientSidebarProvider'
import { SidebarExample } from '@/app/SidebarExample'
import type { Metadata } from 'next'
import { cookies } from 'next/headers'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()

  const defaultOpen = cookieStore.get('sidebar_state')?.value === 'true'

  return (
    <html lang="en">
      <body>
        <ClientAlertProvider>
          <ClientSidebarProvider defaultOpen={defaultOpen}>
            <GlobalAlert />
            <div className="flex h-screen w-full">
              <SidebarExample>{children}</SidebarExample>
            </div>
          </ClientSidebarProvider>
        </ClientAlertProvider>
      </body>
    </html>
  )
}
